interpreter_task:
  description: >
    Analyze the user question and decide whether it should be handled by the Data Analyst or CSV Search Agent.
    Always evaluate the intent and context of the question carefully before delegating.
  expected_output: >
    A clear routing decision indicating which agent should answer the question.
  agent: interpreter

data_analyst_task:
  description: >
    Produce a data-driven answer to the question, focusing on statistical and technical insights from the dataset.
    Always summarize key metrics, trends, and calculations in a concise and actionable format.
  expected_output: >
    An adequate, data-backed answer to the question, presented in a clear and structured report format.
  agent: data_analyst

csv_search_task:
  description: >
    Search for textual information and patterns in the dataset relevant to the user question.
    Always extract the most relevant snippets or matches that answer the query efficiently.
  expected_output: >
    Relevant textual information and context from the dataset that directly addresses the question.
  agent: csv_search

formatter_task:
  description: >
    Combine insights from the Data Analyst and CSV Search agents into a polished, user-friendly answer.
    Ensure the final response is concise, clear, and structured, suitable for end-user consumption.
  expected_output: >
    A final answer that merges all insights into a coherent, readable report for the user.
  agent: formatter
